DELIMITER $
CREATE OR REPLACE PROCEDURE PREPS(IN POPER VARCHAR(1),IN PID INTEGER, IN PNOM VARCHAR(30),IN PESTADO INTEGER)
SP: BEGIN
IF(POPER IN ('Q','U','D')) THEN
SELECT COUNT(*) INTO @B FROM EPS WHERE IDEPS=PID;
IF(@B=0)THEN 
SELECT 'ID NO EXISTE' AS MSG;
LEAVE SP;
END IF;
END IF;

IF (POPER='A') THEN 
SELECT * FROM EPS;
END IF;



IF (POPER='Q')THEN
SELECT * FROM EPS WHERE IDEPS=PID;
END IF;



IF(POPER='I') THEN
INSERT INTO EPS (NOMBRE,ESTADOEPS) VALUES (PNOM,PESTADO);
END IF;


IF(POPER='U') THEN
IF(PNOM IS NULL AND PESTADO IS NOT NULL) THEN
UPDATE EPS SET ESTADOEPS=PESTADO WHERE IDEPS=PID;
END IF;


IF(PNOM IS NOT NULL AND PESTADO IS NULL) THEN
UPDATE EPS SET NOMBRE=PNOM WHERE IDEPS=PID;
END IF;

IF(PNOM IS NOT NULL AND PESTADO IS NOT NULL)THEN
UPDATE EPS SET NOMBRE=PNOM,ESTADOEPS=PESTADO WHERE IDEPS=PID;
END IF;
END IF;



IF(POPER='D') THEN
DELETE FROM EPS WHERE IDEPS=PID;
END IF;



IF(POPER='D') THEN
DELETE FROM EPS WHERE IDEPS=PID;
END IF;
SELECT 'OK' AS MSG;
END;
$
DELIMITER ;